//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.01.08 at 03:07:00 PM CST 
//


package org.jboss.identity.federation.saml.v2.profiles.xacml.assertion;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the oasis.xacml._2_0.saml.assertion.schema.os package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _XACMLAuthzDecisionStatement_QNAME = new QName("urn:oasis:xacml:2.0:saml:assertion:schema:os", "XACMLAuthzDecisionStatement");
    private final static QName _XACMLPolicyStatement_QNAME = new QName("urn:oasis:xacml:2.0:saml:assertion:schema:os", "XACMLPolicyStatement");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: oasis.xacml._2_0.saml.assertion.schema.os
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link XACMLAuthzDecisionStatementType }
     * 
     */
    public XACMLAuthzDecisionStatementType createXACMLAuthzDecisionStatementType() {
        return new XACMLAuthzDecisionStatementType();
    }

    /**
     * Create an instance of {@link XACMLPolicyStatementType }
     * 
     */
    public XACMLPolicyStatementType createXACMLPolicyStatementType() {
        return new XACMLPolicyStatementType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XACMLAuthzDecisionStatementType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:xacml:2.0:saml:assertion:schema:os", name = "XACMLAuthzDecisionStatement")
    public JAXBElement<XACMLAuthzDecisionStatementType> createXACMLAuthzDecisionStatement(XACMLAuthzDecisionStatementType value) {
        return new JAXBElement<XACMLAuthzDecisionStatementType>(_XACMLAuthzDecisionStatement_QNAME, XACMLAuthzDecisionStatementType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XACMLPolicyStatementType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:xacml:2.0:saml:assertion:schema:os", name = "XACMLPolicyStatement")
    public JAXBElement<XACMLPolicyStatementType> createXACMLPolicyStatement(XACMLPolicyStatementType value) {
        return new JAXBElement<XACMLPolicyStatementType>(_XACMLPolicyStatement_QNAME, XACMLPolicyStatementType.class, null, value);
    }

}
