//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.09.03 at 01:21:42 PM BRT  

package org.picketlink.identity.federation.core.config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EncryptionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EncryptionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="EncAlgo" type="{urn:picketlink:identity-federation:config:1.0}EncAlgoType"/>
 *         &lt;element name="KeySize" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EncryptionType", propOrder = {
    "encAlgo",
    "keySize"
})
public class EncryptionType {

    @XmlElement(name = "EncAlgo", required = true)
    protected EncAlgoType encAlgo;
    @XmlElement(name = "KeySize")
    protected int keySize;

    /**
     * Gets the value of the encAlgo property.
     * 
     * @return
     *     possible object is
     *     {@link EncAlgoType }
     *     
     */
    public EncAlgoType getEncAlgo() {
        return encAlgo;
    }

    /**
     * Sets the value of the encAlgo property.
     * 
     * @param value
     *     allowed object is
     *     {@link EncAlgoType }
     *     
     */
    public void setEncAlgo(EncAlgoType value) {
        this.encAlgo = value;
    }

    /**
     * Gets the value of the keySize property.
     * 
     */
    public int getKeySize() {
        return keySize;
    }

    /**
     * Sets the value of the keySize property.
     * 
     */
    public void setKeySize(int value) {
        this.keySize = value;
    }

}
