//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.10.30 at 02:46:25 PM GMT-03:00 
//


package org.picketlink.identity.federation.core.config;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the picketlink.identity_federation.config._1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _picketlinkIDP_QNAME = new QName("urn:picketlink:identity-federation:config:1.0", "PicketLinkIDP");
    private final static QName _PicketLinkSTS_QNAME = new QName("urn:picketlink:identity-federation:config:1.0", "PicketLinkSTS");
    private final static QName _picketlinkSP_QNAME = new QName("urn:picketlink:identity-federation:config:1.0", "PicketLinkSP");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: picketlink.identity_federation.config._1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SPType }
     * 
     */
    public SPType createSPType() {
        return new SPType();
    }

    /**
     * Create an instance of {@link AuthPropertyType }
     * 
     */
    public AuthPropertyType createAuthPropertyType() {
        return new AuthPropertyType();
    }

    /**
     * Create an instance of {@link ServiceProviderType }
     * 
     */
    public ServiceProviderType createServiceProviderType() {
        return new ServiceProviderType();
    }

    /**
     * Create an instance of {@link TrustType }
     * 
     */
    public TrustType createTrustType() {
        return new TrustType();
    }

    /**
     * Create an instance of {@link STSType }
     * 
     */
    public STSType createSTSType() {
        return new STSType();
    }

    /**
     * Create an instance of {@link MetadataProviderType }
     * 
     */
    public MetadataProviderType createMetadataProviderType() {
        return new MetadataProviderType();
    }

    /**
     * Create an instance of {@link TokenProvidersType }
     * 
     */
    public TokenProvidersType createTokenProvidersType() {
        return new TokenProvidersType();
    }

    /**
     * Create an instance of {@link ClaimsProcessorType }
     * 
     */
    public ClaimsProcessorType createClaimsProcessorType() {
        return new ClaimsProcessorType();
    }

    /**
     * Create an instance of {@link ServiceProvidersType }
     * 
     */
    public ServiceProvidersType createServiceProvidersType() {
        return new ServiceProvidersType();
    }

    /**
     * Create an instance of {@link ClaimsProcessorsType }
     * 
     */
    public ClaimsProcessorsType createClaimsProcessorsType() {
        return new ClaimsProcessorsType();
    }

    /**
     * Create an instance of {@link KeyProviderType }
     * 
     */
    public KeyProviderType createKeyProviderType() {
        return new KeyProviderType();
    }

    /**
     * Create an instance of {@link TokenProviderType }
     * 
     */
    public TokenProviderType createTokenProviderType() {
        return new TokenProviderType();
    }

    /**
     * Create an instance of {@link ProviderType }
     * 
     */
    public ProviderType createProviderType() {
        return new ProviderType();
    }

    /**
     * Create an instance of {@link IDPType }
     * 
     */
    public IDPType createIDPType() {
        return new IDPType();
    }

    /**
     * Create an instance of {@link EncryptionType }
     * 
     */
    public EncryptionType createEncryptionType() {
        return new EncryptionType();
    }

    /**
     * Create an instance of {@link KeyValueType }
     * 
     */
    public KeyValueType createKeyValueType() {
        return new KeyValueType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IDPType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:picketlink:identity-federation:config:1.0", name = "PicketLinkIDP")
    public JAXBElement<IDPType> createpicketlinkIDP(IDPType value) {
        return new JAXBElement<IDPType>(_picketlinkIDP_QNAME, IDPType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link STSType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:picketlink:identity-federation:config:1.0", name = "PicketLinkSTS")
    public JAXBElement<STSType> createPicketLinkSTS(STSType value) {
        return new JAXBElement<STSType>(_PicketLinkSTS_QNAME, STSType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SPType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:picketlink:identity-federation:config:1.0", name = "PicketLinkSP")
    public JAXBElement<SPType> createpicketlinkSP(SPType value) {
        return new JAXBElement<SPType>(_picketlinkSP_QNAME, SPType.class, null, value);
    }

}
