//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.10.30 at 02:46:25 PM GMT-03:00 
//


package org.picketlink.identity.federation.core.config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for STSType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="STSType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="KeyProvider" type="{urn:jboss:identity-federation:config:1.0}KeyProviderType" minOccurs="0"/>
 *         &lt;element name="RequestHandler" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ClaimsProcessors" type="{urn:jboss:identity-federation:config:1.0}ClaimsProcessorsType" minOccurs="0"/>
 *         &lt;element name="TokenProviders" type="{urn:jboss:identity-federation:config:1.0}TokenProvidersType" minOccurs="0"/>
 *         &lt;element name="ServiceProviders" type="{urn:jboss:identity-federation:config:1.0}ServiceProvidersType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="STSName" type="{http://www.w3.org/2001/XMLSchema}string" default="JBossSTS" />
 *       &lt;attribute name="TokenTimeout" type="{http://www.w3.org/2001/XMLSchema}int" default="3600" />
 *       &lt;attribute name="SignToken" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="EncryptToken" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "STSType", propOrder = {
    "keyProvider",
    "requestHandler",
    "claimsProcessors",
    "tokenProviders",
    "serviceProviders"
})
public class STSType {

    @XmlElement(name = "KeyProvider")
    protected KeyProviderType keyProvider;
    @XmlElement(name = "RequestHandler")
    protected String requestHandler;
    @XmlElement(name = "ClaimsProcessors")
    protected ClaimsProcessorsType claimsProcessors;
    @XmlElement(name = "TokenProviders")
    protected TokenProvidersType tokenProviders;
    @XmlElement(name = "ServiceProviders")
    protected ServiceProvidersType serviceProviders;
    @XmlAttribute(name = "STSName")
    protected String stsName;
    @XmlAttribute(name = "TokenTimeout")
    protected Integer tokenTimeout;
    @XmlAttribute(name = "SignToken")
    protected Boolean signToken;
    @XmlAttribute(name = "EncryptToken")
    protected Boolean encryptToken;

    /**
     * Gets the value of the keyProvider property.
     * 
     * @return
     *     possible object is
     *     {@link KeyProviderType }
     *     
     */
    public KeyProviderType getKeyProvider() {
        return keyProvider;
    }

    /**
     * Sets the value of the keyProvider property.
     * 
     * @param value
     *     allowed object is
     *     {@link KeyProviderType }
     *     
     */
    public void setKeyProvider(KeyProviderType value) {
        this.keyProvider = value;
    }

    /**
     * Gets the value of the requestHandler property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestHandler() {
        return requestHandler;
    }

    /**
     * Sets the value of the requestHandler property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestHandler(String value) {
        this.requestHandler = value;
    }

    /**
     * Gets the value of the claimsProcessors property.
     * 
     * @return
     *     possible object is
     *     {@link ClaimsProcessorsType }
     *     
     */
    public ClaimsProcessorsType getClaimsProcessors() {
        return claimsProcessors;
    }

    /**
     * Sets the value of the claimsProcessors property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClaimsProcessorsType }
     *     
     */
    public void setClaimsProcessors(ClaimsProcessorsType value) {
        this.claimsProcessors = value;
    }

    /**
     * Gets the value of the tokenProviders property.
     * 
     * @return
     *     possible object is
     *     {@link TokenProvidersType }
     *     
     */
    public TokenProvidersType getTokenProviders() {
        return tokenProviders;
    }

    /**
     * Sets the value of the tokenProviders property.
     * 
     * @param value
     *     allowed object is
     *     {@link TokenProvidersType }
     *     
     */
    public void setTokenProviders(TokenProvidersType value) {
        this.tokenProviders = value;
    }

    /**
     * Gets the value of the serviceProviders property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceProvidersType }
     *     
     */
    public ServiceProvidersType getServiceProviders() {
        return serviceProviders;
    }

    /**
     * Sets the value of the serviceProviders property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceProvidersType }
     *     
     */
    public void setServiceProviders(ServiceProvidersType value) {
        this.serviceProviders = value;
    }

    /**
     * Gets the value of the stsName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTSName() {
        if (stsName == null) {
            return "JBossSTS";
        } else {
            return stsName;
        }
    }

    /**
     * Sets the value of the stsName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTSName(String value) {
        this.stsName = value;
    }

    /**
     * Gets the value of the tokenTimeout property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getTokenTimeout() {
        if (tokenTimeout == null) {
            return  3600;
        } else {
            return tokenTimeout;
        }
    }

    /**
     * Sets the value of the tokenTimeout property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTokenTimeout(Integer value) {
        this.tokenTimeout = value;
    }

    /**
     * Gets the value of the signToken property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isSignToken() {
        if (signToken == null) {
            return true;
        } else {
            return signToken;
        }
    }

    /**
     * Sets the value of the signToken property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSignToken(Boolean value) {
        this.signToken = value;
    }

    /**
     * Gets the value of the encryptToken property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isEncryptToken() {
        if (encryptToken == null) {
            return false;
        } else {
            return encryptToken;
        }
    }

    /**
     * Sets the value of the encryptToken property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setEncryptToken(Boolean value) {
        this.encryptToken = value;
    }

}
