//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema.  
// Generated on: 2009.09.03 at 01:21:42 PM BRT  
//


package org.picketlink.identity.federation.core.config;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				The token providers specify the classes that handle the requests for each type of security Token.
 * 				For example, a SAMLTokenProvider may be used to generate SAML token, while a X509TokenProvider
 * 				may be used to generate X.509 tokens (certificates).
 * 			
 * 
 * <p>Java class for TokenProvidersType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TokenProvidersType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TokenProvider" type="{urn:picketlink:identity-federation:config:1.0}TokenProviderType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TokenProvidersType", propOrder = {
    "tokenProvider"
})
public class TokenProvidersType {

    @XmlElement(name = "TokenProvider", required = true)
    protected List<TokenProviderType> tokenProvider;

    /**
     * Gets the value of the tokenProvider property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tokenProvider property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTokenProvider().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TokenProviderType }
     * 
     * 
     */
    public List<TokenProviderType> getTokenProvider() {
        if (tokenProvider == null) {
            tokenProvider = new ArrayList<TokenProviderType>();
        }
        return this.tokenProvider;
    }

}
