//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.10.06 at 02:14:55 PM CDT 
//


package org.picketlink.identity.federation.core.handler.config;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the jboss.identity_federation.handler.config._1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Handlers_QNAME = new QName("urn:jboss:identity-federation:handler:config:1.0", "Handlers");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: jboss.identity_federation.handler.config._1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Handler }
     * 
     */
    public Handler createHandler() {
        return new Handler();
    }

    /**
     * Create an instance of {@link Handlers }
     * 
     */
    public Handlers createHandlers() {
        return new Handlers();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Handlers }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:jboss:identity-federation:handler:config:1.0", name = "Handlers")
    public JAXBElement<Handlers> createHandlers(Handlers value) {
        return new JAXBElement<Handlers>(_Handlers_QNAME, Handlers.class, null, value);
    }

}
