//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.02.06 at 12:47:37 AM CET 
//


package org.picketlink.identity.seam.federation.config.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				Configuration for the external authentication of users
 * 				(using for example SAMLv2 or OpenID).
 * 			
 * 
 * <p>Java class for ExternalAuthenticationConfigType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ExternalAuthenticationConfigType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="ServiceProvider" type="{urn:picketlink:identity-federation:seam:config:1.0}ServiceProviderType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExternalAuthenticationConfigType", propOrder = {
    "serviceProvider"
})
public class ExternalAuthenticationConfigType {

    @XmlElement(name = "ServiceProvider")
    protected List<ServiceProviderType> serviceProvider;

    /**
     * Gets the value of the serviceProvider property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the serviceProvider property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getServiceProvider().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ServiceProviderType }
     * 
     * 
     */
    public List<ServiceProviderType> getServiceProvider() {
        if (serviceProvider == null) {
            serviceProvider = new ArrayList<ServiceProviderType>();
        }
        return this.serviceProvider;
    }

}
