//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.02.06 at 12:47:37 AM CET 
//


package org.picketlink.identity.seam.federation.config.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.picketlink.identity.seam.federation.config.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ExternalAuthenticationConfig_QNAME = new QName("urn:picketlink:identity-federation:seam:config:1.0", "ExternalAuthenticationConfig");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.picketlink.identity.seam.federation.config.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SamlConfigType }
     * 
     */
    public SamlConfigType createSamlConfigType() {
        return new SamlConfigType();
    }

    /**
     * Create an instance of {@link OpenIdAttributeType }
     * 
     */
    public OpenIdAttributeType createOpenIdAttributeType() {
        return new OpenIdAttributeType();
    }

    /**
     * Create an instance of {@link ServiceProviderType }
     * 
     */
    public ServiceProviderType createServiceProviderType() {
        return new ServiceProviderType();
    }

    /**
     * Create an instance of {@link ExternalAuthenticationConfigType }
     * 
     */
    public ExternalAuthenticationConfigType createExternalAuthenticationConfigType() {
        return new ExternalAuthenticationConfigType();
    }

    /**
     * Create an instance of {@link SamlIdentityProviderType }
     * 
     */
    public SamlIdentityProviderType createSamlIdentityProviderType() {
        return new SamlIdentityProviderType();
    }

    /**
     * Create an instance of {@link OpenIdConfigType }
     * 
     */
    public OpenIdConfigType createOpenIdConfigType() {
        return new OpenIdConfigType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExternalAuthenticationConfigType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:picketlink:identity-federation:seam:config:1.0", name = "ExternalAuthenticationConfig")
    public JAXBElement<ExternalAuthenticationConfigType> createExternalAuthenticationConfig(ExternalAuthenticationConfigType value) {
        return new JAXBElement<ExternalAuthenticationConfigType>(_ExternalAuthenticationConfig_QNAME, ExternalAuthenticationConfigType.class, null, value);
    }

}
