//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.02.06 at 12:47:37 AM CET 
//


package org.picketlink.identity.seam.federation.config.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SamlIdentityProviderType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SamlIdentityProviderType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="entityId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="singleLogoutMessagesSigned" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="wantSingleLogoutMessagesSigned" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SamlIdentityProviderType")
public class SamlIdentityProviderType {

    @XmlAttribute(required = true)
    protected String entityId;
    @XmlAttribute
    protected Boolean singleLogoutMessagesSigned;
    @XmlAttribute
    protected Boolean wantSingleLogoutMessagesSigned;

    /**
     * Gets the value of the entityId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntityId() {
        return entityId;
    }

    /**
     * Sets the value of the entityId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntityId(String value) {
        this.entityId = value;
    }

    /**
     * Gets the value of the singleLogoutMessagesSigned property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isSingleLogoutMessagesSigned() {
        if (singleLogoutMessagesSigned == null) {
            return false;
        } else {
            return singleLogoutMessagesSigned;
        }
    }

    /**
     * Sets the value of the singleLogoutMessagesSigned property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSingleLogoutMessagesSigned(Boolean value) {
        this.singleLogoutMessagesSigned = value;
    }

    /**
     * Gets the value of the wantSingleLogoutMessagesSigned property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isWantSingleLogoutMessagesSigned() {
        if (wantSingleLogoutMessagesSigned == null) {
            return false;
        } else {
            return wantSingleLogoutMessagesSigned;
        }
    }

    /**
     * Sets the value of the wantSingleLogoutMessagesSigned property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setWantSingleLogoutMessagesSigned(Boolean value) {
        this.wantSingleLogoutMessagesSigned = value;
    }

}
