//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.02.06 at 12:47:37 AM CET 
//


package org.picketlink.identity.seam.federation.config.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				Configuration for SAMLv2.
 * 			
 * 
 * <p>Java class for SamlConfigType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SamlConfigType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="SamlIdentityProvider" type="{urn:picketlink:identity-federation:seam:config:1.0}SamlIdentityProviderType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="authnRequestsSigned" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="wantAssertionsSigned" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="serviceProviderEntityId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="defaultIdentityProvider" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="keyStoreUrl" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="keyStorePass" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="signingKeyAlias" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="signingKeyPass" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SamlConfigType", propOrder = {
    "samlIdentityProvider"
})
public class SamlConfigType {

    @XmlElement(name = "SamlIdentityProvider")
    protected List<SamlIdentityProviderType> samlIdentityProvider;
    @XmlAttribute
    protected Boolean authnRequestsSigned;
    @XmlAttribute
    protected Boolean wantAssertionsSigned;
    @XmlAttribute(required = true)
    protected String serviceProviderEntityId;
    @XmlAttribute
    protected String defaultIdentityProvider;
    @XmlAttribute(required = true)
    protected String keyStoreUrl;
    @XmlAttribute(required = true)
    protected String keyStorePass;
    @XmlAttribute(required = true)
    protected String signingKeyAlias;
    @XmlAttribute
    protected String signingKeyPass;

    /**
     * Gets the value of the samlIdentityProvider property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the samlIdentityProvider property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSamlIdentityProvider().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SamlIdentityProviderType }
     * 
     * 
     */
    public List<SamlIdentityProviderType> getSamlIdentityProvider() {
        if (samlIdentityProvider == null) {
            samlIdentityProvider = new ArrayList<SamlIdentityProviderType>();
        }
        return this.samlIdentityProvider;
    }

    /**
     * Gets the value of the authnRequestsSigned property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isAuthnRequestsSigned() {
        if (authnRequestsSigned == null) {
            return false;
        } else {
            return authnRequestsSigned;
        }
    }

    /**
     * Sets the value of the authnRequestsSigned property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAuthnRequestsSigned(Boolean value) {
        this.authnRequestsSigned = value;
    }

    /**
     * Gets the value of the wantAssertionsSigned property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isWantAssertionsSigned() {
        if (wantAssertionsSigned == null) {
            return true;
        } else {
            return wantAssertionsSigned;
        }
    }

    /**
     * Sets the value of the wantAssertionsSigned property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setWantAssertionsSigned(Boolean value) {
        this.wantAssertionsSigned = value;
    }

    /**
     * Gets the value of the serviceProviderEntityId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceProviderEntityId() {
        return serviceProviderEntityId;
    }

    /**
     * Sets the value of the serviceProviderEntityId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceProviderEntityId(String value) {
        this.serviceProviderEntityId = value;
    }

    /**
     * Gets the value of the defaultIdentityProvider property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultIdentityProvider() {
        return defaultIdentityProvider;
    }

    /**
     * Sets the value of the defaultIdentityProvider property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultIdentityProvider(String value) {
        this.defaultIdentityProvider = value;
    }

    /**
     * Gets the value of the keyStoreUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKeyStoreUrl() {
        return keyStoreUrl;
    }

    /**
     * Sets the value of the keyStoreUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKeyStoreUrl(String value) {
        this.keyStoreUrl = value;
    }

    /**
     * Gets the value of the keyStorePass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKeyStorePass() {
        return keyStorePass;
    }

    /**
     * Sets the value of the keyStorePass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKeyStorePass(String value) {
        this.keyStorePass = value;
    }

    /**
     * Gets the value of the signingKeyAlias property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSigningKeyAlias() {
        return signingKeyAlias;
    }

    /**
     * Sets the value of the signingKeyAlias property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSigningKeyAlias(String value) {
        this.signingKeyAlias = value;
    }

    /**
     * Gets the value of the signingKeyPass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSigningKeyPass() {
        return signingKeyPass;
    }

    /**
     * Sets the value of the signingKeyPass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSigningKeyPass(String value) {
        this.signingKeyPass = value;
    }

}
