//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.12.08 at 05:45:20 PM CST 
//


package org.picketlink.identity.federation.saml.v2.ac.classes.x509;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the oasis.names.tc.saml._2_0.ac.classes.x509 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _KeyActivation_QNAME = new QName("urn:oasis:names:tc:SAML:2.0:ac:classes:X509", "KeyActivation");
    private final static QName _Alphabet_QNAME = new QName("urn:oasis:names:tc:SAML:2.0:ac:classes:X509", "Alphabet");
    private final static QName _ISDN_QNAME = new QName("urn:oasis:names:tc:SAML:2.0:ac:classes:X509", "ISDN");
    private final static QName _AuthnMethod_QNAME = new QName("urn:oasis:names:tc:SAML:2.0:ac:classes:X509", "AuthnMethod");
    private final static QName _SwitchAudit_QNAME = new QName("urn:oasis:names:tc:SAML:2.0:ac:classes:X509", "SwitchAudit");
    private final static QName _SSL_QNAME = new QName("urn:oasis:names:tc:SAML:2.0:ac:classes:X509", "SSL");
    private final static QName _UserSuffix_QNAME = new QName("urn:oasis:names:tc:SAML:2.0:ac:classes:X509", "UserSuffix");
    private final static QName _HTTP_QNAME = new QName("urn:oasis:names:tc:SAML:2.0:ac:classes:X509", "HTTP");
    private final static QName _GoverningAgreementRef_QNAME = new QName("urn:oasis:names:tc:SAML:2.0:ac:classes:X509", "GoverningAgreementRef");
    private final static QName _Extension_QNAME = new QName("urn:oasis:names:tc:SAML:2.0:ac:classes:X509", "Extension");
    private final static QName _MobileNetworkEndToEndEncryption_QNAME = new QName("urn:oasis:names:tc:SAML:2.0:ac:classes:X509", "MobileNetworkEndToEndEncryption");
    private final static QName _Token_QNAME = new QName("urn:oasis:names:tc:SAML:2.0:ac:classes:X509", "Token");
    private final static QName _Password_QNAME = new QName("urn:oasis:names:tc:SAML:2.0:ac:classes:X509", "Password");
    private final static QName _MobileNetworkNoEncryption_QNAME = new QName("urn:oasis:names:tc:SAML:2.0:ac:classes:X509", "MobileNetworkNoEncryption");
    private final static QName _KeyStorage_QNAME = new QName("urn:oasis:names:tc:SAML:2.0:ac:classes:X509", "KeyStorage");
    private final static QName _Smartcard_QNAME = new QName("urn:oasis:names:tc:SAML:2.0:ac:classes:X509", "Smartcard");
    private final static QName _OperationalProtection_QNAME = new QName("urn:oasis:names:tc:SAML:2.0:ac:classes:X509", "OperationalProtection");
    private final static QName _ActivationLimit_QNAME = new QName("urn:oasis:names:tc:SAML:2.0:ac:classes:X509", "ActivationLimit");
    private final static QName _TechnicalProtection_QNAME = new QName("urn:oasis:names:tc:SAML:2.0:ac:classes:X509", "TechnicalProtection");
    private final static QName _Authenticator_QNAME = new QName("urn:oasis:names:tc:SAML:2.0:ac:classes:X509", "Authenticator");
    private final static QName _TimeSyncToken_QNAME = new QName("urn:oasis:names:tc:SAML:2.0:ac:classes:X509", "TimeSyncToken");
    private final static QName _ActivationLimitUsages_QNAME = new QName("urn:oasis:names:tc:SAML:2.0:ac:classes:X509", "ActivationLimitUsages");
    private final static QName _GoverningAgreements_QNAME = new QName("urn:oasis:names:tc:SAML:2.0:ac:classes:X509", "GoverningAgreements");
    private final static QName _Identification_QNAME = new QName("urn:oasis:names:tc:SAML:2.0:ac:classes:X509", "Identification");
    private final static QName _PreviousSession_QNAME = new QName("urn:oasis:names:tc:SAML:2.0:ac:classes:X509", "PreviousSession");
    private final static QName _IPAddress_QNAME = new QName("urn:oasis:names:tc:SAML:2.0:ac:classes:X509", "IPAddress");
    private final static QName _ActivationPin_QNAME = new QName("urn:oasis:names:tc:SAML:2.0:ac:classes:X509", "ActivationPin");
    private final static QName _ResumeSession_QNAME = new QName("urn:oasis:names:tc:SAML:2.0:ac:classes:X509", "ResumeSession");
    private final static QName _IPSec_QNAME = new QName("urn:oasis:names:tc:SAML:2.0:ac:classes:X509", "IPSec");
    private final static QName _MobileNetworkRadioEncryption_QNAME = new QName("urn:oasis:names:tc:SAML:2.0:ac:classes:X509", "MobileNetworkRadioEncryption");
    private final static QName _PSTN_QNAME = new QName("urn:oasis:names:tc:SAML:2.0:ac:classes:X509", "PSTN");
    private final static QName _WrittenConsent_QNAME = new QName("urn:oasis:names:tc:SAML:2.0:ac:classes:X509", "WrittenConsent");
    private final static QName _DeactivationCallCenter_QNAME = new QName("urn:oasis:names:tc:SAML:2.0:ac:classes:X509", "DeactivationCallCenter");
    private final static QName _ZeroKnowledge_QNAME = new QName("urn:oasis:names:tc:SAML:2.0:ac:classes:X509", "ZeroKnowledge");
    private final static QName _PrincipalAuthenticationMechanism_QNAME = new QName("urn:oasis:names:tc:SAML:2.0:ac:classes:X509", "PrincipalAuthenticationMechanism");
    private final static QName _ComplexAuthenticator_QNAME = new QName("urn:oasis:names:tc:SAML:2.0:ac:classes:X509", "ComplexAuthenticator");
    private final static QName _ADSL_QNAME = new QName("urn:oasis:names:tc:SAML:2.0:ac:classes:X509", "ADSL");
    private final static QName _RestrictedPassword_QNAME = new QName("urn:oasis:names:tc:SAML:2.0:ac:classes:X509", "RestrictedPassword");
    private final static QName _SharedSecretChallengeResponse_QNAME = new QName("urn:oasis:names:tc:SAML:2.0:ac:classes:X509", "SharedSecretChallengeResponse");
    private final static QName _SecretKeyProtection_QNAME = new QName("urn:oasis:names:tc:SAML:2.0:ac:classes:X509", "SecretKeyProtection");
    private final static QName _AsymmetricDecryption_QNAME = new QName("urn:oasis:names:tc:SAML:2.0:ac:classes:X509", "AsymmetricDecryption");
    private final static QName _DigSig_QNAME = new QName("urn:oasis:names:tc:SAML:2.0:ac:classes:X509", "DigSig");
    private final static QName _Length_QNAME = new QName("urn:oasis:names:tc:SAML:2.0:ac:classes:X509", "Length");
    private final static QName _SubscriberLineNumber_QNAME = new QName("urn:oasis:names:tc:SAML:2.0:ac:classes:X509", "SubscriberLineNumber");
    private final static QName _SecurityAudit_QNAME = new QName("urn:oasis:names:tc:SAML:2.0:ac:classes:X509", "SecurityAudit");
    private final static QName _ActivationLimitDuration_QNAME = new QName("urn:oasis:names:tc:SAML:2.0:ac:classes:X509", "ActivationLimitDuration");
    private final static QName _KeySharing_QNAME = new QName("urn:oasis:names:tc:SAML:2.0:ac:classes:X509", "KeySharing");
    private final static QName _AuthenticationContextDeclaration_QNAME = new QName("urn:oasis:names:tc:SAML:2.0:ac:classes:X509", "AuthenticationContextDeclaration");
    private final static QName _AsymmetricKeyAgreement_QNAME = new QName("urn:oasis:names:tc:SAML:2.0:ac:classes:X509", "AsymmetricKeyAgreement");
    private final static QName _WTLS_QNAME = new QName("urn:oasis:names:tc:SAML:2.0:ac:classes:X509", "WTLS");
    private final static QName _PrivateKeyProtection_QNAME = new QName("urn:oasis:names:tc:SAML:2.0:ac:classes:X509", "PrivateKeyProtection");
    private final static QName _SharedSecretDynamicPlaintext_QNAME = new QName("urn:oasis:names:tc:SAML:2.0:ac:classes:X509", "SharedSecretDynamicPlaintext");
    private final static QName _ActivationLimitSession_QNAME = new QName("urn:oasis:names:tc:SAML:2.0:ac:classes:X509", "ActivationLimitSession");
    private final static QName _AuthenticatorTransportProtocol_QNAME = new QName("urn:oasis:names:tc:SAML:2.0:ac:classes:X509", "AuthenticatorTransportProtocol");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: oasis.names.tc.saml._2_0.ac.classes.x509
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ActivationLimitSessionType }
     * 
     */
    public ActivationLimitSessionType createActivationLimitSessionType() {
        return new ActivationLimitSessionType();
    }

    /**
     * Create an instance of {@link PrivateKeyProtectionType }
     * 
     */
    public PrivateKeyProtectionType createPrivateKeyProtectionType() {
        return new PrivateKeyProtectionType();
    }

    /**
     * Create an instance of {@link GoverningAgreementsType }
     * 
     */
    public GoverningAgreementsType createGoverningAgreementsType() {
        return new GoverningAgreementsType();
    }

    /**
     * Create an instance of {@link ActivationPinType }
     * 
     */
    public ActivationPinType createActivationPinType() {
        return new ActivationPinType();
    }

    /**
     * Create an instance of {@link AlphabetType }
     * 
     */
    public AlphabetType createAlphabetType() {
        return new AlphabetType();
    }

    /**
     * Create an instance of {@link RestrictedPasswordType }
     * 
     */
    public RestrictedPasswordType createRestrictedPasswordType() {
        return new RestrictedPasswordType();
    }

    /**
     * Create an instance of {@link TokenType }
     * 
     */
    public TokenType createTokenType() {
        return new TokenType();
    }

    /**
     * Create an instance of {@link SharedSecretChallengeResponseType }
     * 
     */
    public SharedSecretChallengeResponseType createSharedSecretChallengeResponseType() {
        return new SharedSecretChallengeResponseType();
    }

    /**
     * Create an instance of {@link OperationalProtectionType }
     * 
     */
    public OperationalProtectionType createOperationalProtectionType() {
        return new OperationalProtectionType();
    }

    /**
     * Create an instance of {@link Generation }
     * 
     */
    public Generation createGeneration() {
        return new Generation();
    }

    /**
     * Create an instance of {@link LengthType }
     * 
     */
    public LengthType createLengthType() {
        return new LengthType();
    }

    /**
     * Create an instance of {@link RestrictedLengthType }
     * 
     */
    public RestrictedLengthType createRestrictedLengthType() {
        return new RestrictedLengthType();
    }

    /**
     * Create an instance of {@link SecretKeyProtectionType }
     * 
     */
    public SecretKeyProtectionType createSecretKeyProtectionType() {
        return new SecretKeyProtectionType();
    }

    /**
     * Create an instance of {@link PublicKeyType }
     * 
     */
    public PublicKeyType createPublicKeyType() {
        return new PublicKeyType();
    }

    /**
     * Create an instance of {@link AuthenticatorBaseType }
     * 
     */
    public AuthenticatorBaseType createAuthenticatorBaseType() {
        return new AuthenticatorBaseType();
    }

    /**
     * Create an instance of {@link OriginalAuthnMethodBaseType }
     * 
     */
    public OriginalAuthnMethodBaseType createOriginalAuthnMethodBaseType() {
        return new OriginalAuthnMethodBaseType();
    }

    /**
     * Create an instance of {@link OriginalPublicKeyType }
     * 
     */
    public OriginalPublicKeyType createOriginalPublicKeyType() {
        return new OriginalPublicKeyType();
    }

    /**
     * Create an instance of {@link OriginalAuthnContextDeclarationBaseType }
     * 
     */
    public OriginalAuthnContextDeclarationBaseType createOriginalAuthnContextDeclarationBaseType() {
        return new OriginalAuthnContextDeclarationBaseType();
    }

    /**
     * Create an instance of {@link ActivationLimitDurationType }
     * 
     */
    public ActivationLimitDurationType createActivationLimitDurationType() {
        return new ActivationLimitDurationType();
    }

    /**
     * Create an instance of {@link AuthenticatorTransportProtocolType }
     * 
     */
    public AuthenticatorTransportProtocolType createAuthenticatorTransportProtocolType() {
        return new AuthenticatorTransportProtocolType();
    }

    /**
     * Create an instance of {@link SecurityAuditType }
     * 
     */
    public SecurityAuditType createSecurityAuditType() {
        return new SecurityAuditType();
    }

    /**
     * Create an instance of {@link KeyActivationType }
     * 
     */
    public KeyActivationType createKeyActivationType() {
        return new KeyActivationType();
    }

    /**
     * Create an instance of {@link PhysicalVerification }
     * 
     */
    public PhysicalVerification createPhysicalVerification() {
        return new PhysicalVerification();
    }

    /**
     * Create an instance of {@link PasswordType }
     * 
     */
    public PasswordType createPasswordType() {
        return new PasswordType();
    }

    /**
     * Create an instance of {@link ActivationLimitType }
     * 
     */
    public ActivationLimitType createActivationLimitType() {
        return new ActivationLimitType();
    }

    /**
     * Create an instance of {@link OriginalAuthenticatorBaseType }
     * 
     */
    public OriginalAuthenticatorBaseType createOriginalAuthenticatorBaseType() {
        return new OriginalAuthenticatorBaseType();
    }

    /**
     * Create an instance of {@link ExtensionType }
     * 
     */
    public ExtensionType createExtensionType() {
        return new ExtensionType();
    }

    /**
     * Create an instance of {@link ComplexAuthenticatorType }
     * 
     */
    public ComplexAuthenticatorType createComplexAuthenticatorType() {
        return new ComplexAuthenticatorType();
    }

    /**
     * Create an instance of {@link KeySharingType }
     * 
     */
    public KeySharingType createKeySharingType() {
        return new KeySharingType();
    }

    /**
     * Create an instance of {@link AuthnMethodBaseType }
     * 
     */
    public AuthnMethodBaseType createAuthnMethodBaseType() {
        return new AuthnMethodBaseType();
    }

    /**
     * Create an instance of {@link OriginalPrincipalAuthenticationMechanismType }
     * 
     */
    public OriginalPrincipalAuthenticationMechanismType createOriginalPrincipalAuthenticationMechanismType() {
        return new OriginalPrincipalAuthenticationMechanismType();
    }

    /**
     * Create an instance of {@link TimeSyncTokenType }
     * 
     */
    public TimeSyncTokenType createTimeSyncTokenType() {
        return new TimeSyncTokenType();
    }

    /**
     * Create an instance of {@link ActivationLimitUsagesType }
     * 
     */
    public ActivationLimitUsagesType createActivationLimitUsagesType() {
        return new ActivationLimitUsagesType();
    }

    /**
     * Create an instance of {@link GoverningAgreementRefType }
     * 
     */
    public GoverningAgreementRefType createGoverningAgreementRefType() {
        return new GoverningAgreementRefType();
    }

    /**
     * Create an instance of {@link ExtensionOnlyType }
     * 
     */
    public ExtensionOnlyType createExtensionOnlyType() {
        return new ExtensionOnlyType();
    }

    /**
     * Create an instance of {@link PrincipalAuthenticationMechanismType }
     * 
     */
    public PrincipalAuthenticationMechanismType createPrincipalAuthenticationMechanismType() {
        return new PrincipalAuthenticationMechanismType();
    }

    /**
     * Create an instance of {@link IdentificationType }
     * 
     */
    public IdentificationType createIdentificationType() {
        return new IdentificationType();
    }

    /**
     * Create an instance of {@link AuthnContextDeclarationBaseType }
     * 
     */
    public AuthnContextDeclarationBaseType createAuthnContextDeclarationBaseType() {
        return new AuthnContextDeclarationBaseType();
    }

    /**
     * Create an instance of {@link KeyStorageType }
     * 
     */
    public KeyStorageType createKeyStorageType() {
        return new KeyStorageType();
    }

    /**
     * Create an instance of {@link TechnicalProtectionBaseType }
     * 
     */
    public TechnicalProtectionBaseType createTechnicalProtectionBaseType() {
        return new TechnicalProtectionBaseType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link KeyActivationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:SAML:2.0:ac:classes:X509", name = "KeyActivation")
    public JAXBElement<KeyActivationType> createKeyActivation(KeyActivationType value) {
        return new JAXBElement<KeyActivationType>(_KeyActivation_QNAME, KeyActivationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AlphabetType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:SAML:2.0:ac:classes:X509", name = "Alphabet")
    public JAXBElement<AlphabetType> createAlphabet(AlphabetType value) {
        return new JAXBElement<AlphabetType>(_Alphabet_QNAME, AlphabetType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExtensionOnlyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:SAML:2.0:ac:classes:X509", name = "ISDN")
    public JAXBElement<ExtensionOnlyType> createISDN(ExtensionOnlyType value) {
        return new JAXBElement<ExtensionOnlyType>(_ISDN_QNAME, ExtensionOnlyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AuthnMethodBaseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:SAML:2.0:ac:classes:X509", name = "AuthnMethod")
    public JAXBElement<AuthnMethodBaseType> createAuthnMethod(AuthnMethodBaseType value) {
        return new JAXBElement<AuthnMethodBaseType>(_AuthnMethod_QNAME, AuthnMethodBaseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExtensionOnlyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:SAML:2.0:ac:classes:X509", name = "SwitchAudit")
    public JAXBElement<ExtensionOnlyType> createSwitchAudit(ExtensionOnlyType value) {
        return new JAXBElement<ExtensionOnlyType>(_SwitchAudit_QNAME, ExtensionOnlyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExtensionOnlyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:SAML:2.0:ac:classes:X509", name = "SSL")
    public JAXBElement<ExtensionOnlyType> createSSL(ExtensionOnlyType value) {
        return new JAXBElement<ExtensionOnlyType>(_SSL_QNAME, ExtensionOnlyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExtensionOnlyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:SAML:2.0:ac:classes:X509", name = "UserSuffix")
    public JAXBElement<ExtensionOnlyType> createUserSuffix(ExtensionOnlyType value) {
        return new JAXBElement<ExtensionOnlyType>(_UserSuffix_QNAME, ExtensionOnlyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExtensionOnlyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:SAML:2.0:ac:classes:X509", name = "HTTP")
    public JAXBElement<ExtensionOnlyType> createHTTP(ExtensionOnlyType value) {
        return new JAXBElement<ExtensionOnlyType>(_HTTP_QNAME, ExtensionOnlyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GoverningAgreementRefType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:SAML:2.0:ac:classes:X509", name = "GoverningAgreementRef")
    public JAXBElement<GoverningAgreementRefType> createGoverningAgreementRef(GoverningAgreementRefType value) {
        return new JAXBElement<GoverningAgreementRefType>(_GoverningAgreementRef_QNAME, GoverningAgreementRefType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExtensionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:SAML:2.0:ac:classes:X509", name = "Extension")
    public JAXBElement<ExtensionType> createExtension(ExtensionType value) {
        return new JAXBElement<ExtensionType>(_Extension_QNAME, ExtensionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExtensionOnlyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:SAML:2.0:ac:classes:X509", name = "MobileNetworkEndToEndEncryption")
    public JAXBElement<ExtensionOnlyType> createMobileNetworkEndToEndEncryption(ExtensionOnlyType value) {
        return new JAXBElement<ExtensionOnlyType>(_MobileNetworkEndToEndEncryption_QNAME, ExtensionOnlyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TokenType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:SAML:2.0:ac:classes:X509", name = "Token")
    public JAXBElement<TokenType> createToken(TokenType value) {
        return new JAXBElement<TokenType>(_Token_QNAME, TokenType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PasswordType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:SAML:2.0:ac:classes:X509", name = "Password")
    public JAXBElement<PasswordType> createPassword(PasswordType value) {
        return new JAXBElement<PasswordType>(_Password_QNAME, PasswordType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExtensionOnlyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:SAML:2.0:ac:classes:X509", name = "MobileNetworkNoEncryption")
    public JAXBElement<ExtensionOnlyType> createMobileNetworkNoEncryption(ExtensionOnlyType value) {
        return new JAXBElement<ExtensionOnlyType>(_MobileNetworkNoEncryption_QNAME, ExtensionOnlyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link KeyStorageType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:SAML:2.0:ac:classes:X509", name = "KeyStorage")
    public JAXBElement<KeyStorageType> createKeyStorage(KeyStorageType value) {
        return new JAXBElement<KeyStorageType>(_KeyStorage_QNAME, KeyStorageType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExtensionOnlyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:SAML:2.0:ac:classes:X509", name = "Smartcard")
    public JAXBElement<ExtensionOnlyType> createSmartcard(ExtensionOnlyType value) {
        return new JAXBElement<ExtensionOnlyType>(_Smartcard_QNAME, ExtensionOnlyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OperationalProtectionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:SAML:2.0:ac:classes:X509", name = "OperationalProtection")
    public JAXBElement<OperationalProtectionType> createOperationalProtection(OperationalProtectionType value) {
        return new JAXBElement<OperationalProtectionType>(_OperationalProtection_QNAME, OperationalProtectionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ActivationLimitType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:SAML:2.0:ac:classes:X509", name = "ActivationLimit")
    public JAXBElement<ActivationLimitType> createActivationLimit(ActivationLimitType value) {
        return new JAXBElement<ActivationLimitType>(_ActivationLimit_QNAME, ActivationLimitType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TechnicalProtectionBaseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:SAML:2.0:ac:classes:X509", name = "TechnicalProtection")
    public JAXBElement<TechnicalProtectionBaseType> createTechnicalProtection(TechnicalProtectionBaseType value) {
        return new JAXBElement<TechnicalProtectionBaseType>(_TechnicalProtection_QNAME, TechnicalProtectionBaseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AuthenticatorBaseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:SAML:2.0:ac:classes:X509", name = "Authenticator")
    public JAXBElement<AuthenticatorBaseType> createAuthenticator(AuthenticatorBaseType value) {
        return new JAXBElement<AuthenticatorBaseType>(_Authenticator_QNAME, AuthenticatorBaseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TimeSyncTokenType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:SAML:2.0:ac:classes:X509", name = "TimeSyncToken")
    public JAXBElement<TimeSyncTokenType> createTimeSyncToken(TimeSyncTokenType value) {
        return new JAXBElement<TimeSyncTokenType>(_TimeSyncToken_QNAME, TimeSyncTokenType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ActivationLimitUsagesType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:SAML:2.0:ac:classes:X509", name = "ActivationLimitUsages")
    public JAXBElement<ActivationLimitUsagesType> createActivationLimitUsages(ActivationLimitUsagesType value) {
        return new JAXBElement<ActivationLimitUsagesType>(_ActivationLimitUsages_QNAME, ActivationLimitUsagesType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GoverningAgreementsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:SAML:2.0:ac:classes:X509", name = "GoverningAgreements")
    public JAXBElement<GoverningAgreementsType> createGoverningAgreements(GoverningAgreementsType value) {
        return new JAXBElement<GoverningAgreementsType>(_GoverningAgreements_QNAME, GoverningAgreementsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IdentificationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:SAML:2.0:ac:classes:X509", name = "Identification")
    public JAXBElement<IdentificationType> createIdentification(IdentificationType value) {
        return new JAXBElement<IdentificationType>(_Identification_QNAME, IdentificationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExtensionOnlyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:SAML:2.0:ac:classes:X509", name = "PreviousSession")
    public JAXBElement<ExtensionOnlyType> createPreviousSession(ExtensionOnlyType value) {
        return new JAXBElement<ExtensionOnlyType>(_PreviousSession_QNAME, ExtensionOnlyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExtensionOnlyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:SAML:2.0:ac:classes:X509", name = "IPAddress")
    public JAXBElement<ExtensionOnlyType> createIPAddress(ExtensionOnlyType value) {
        return new JAXBElement<ExtensionOnlyType>(_IPAddress_QNAME, ExtensionOnlyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ActivationPinType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:SAML:2.0:ac:classes:X509", name = "ActivationPin")
    public JAXBElement<ActivationPinType> createActivationPin(ActivationPinType value) {
        return new JAXBElement<ActivationPinType>(_ActivationPin_QNAME, ActivationPinType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExtensionOnlyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:SAML:2.0:ac:classes:X509", name = "ResumeSession")
    public JAXBElement<ExtensionOnlyType> createResumeSession(ExtensionOnlyType value) {
        return new JAXBElement<ExtensionOnlyType>(_ResumeSession_QNAME, ExtensionOnlyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExtensionOnlyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:SAML:2.0:ac:classes:X509", name = "IPSec")
    public JAXBElement<ExtensionOnlyType> createIPSec(ExtensionOnlyType value) {
        return new JAXBElement<ExtensionOnlyType>(_IPSec_QNAME, ExtensionOnlyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExtensionOnlyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:SAML:2.0:ac:classes:X509", name = "MobileNetworkRadioEncryption")
    public JAXBElement<ExtensionOnlyType> createMobileNetworkRadioEncryption(ExtensionOnlyType value) {
        return new JAXBElement<ExtensionOnlyType>(_MobileNetworkRadioEncryption_QNAME, ExtensionOnlyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExtensionOnlyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:SAML:2.0:ac:classes:X509", name = "PSTN")
    public JAXBElement<ExtensionOnlyType> createPSTN(ExtensionOnlyType value) {
        return new JAXBElement<ExtensionOnlyType>(_PSTN_QNAME, ExtensionOnlyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExtensionOnlyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:SAML:2.0:ac:classes:X509", name = "WrittenConsent")
    public JAXBElement<ExtensionOnlyType> createWrittenConsent(ExtensionOnlyType value) {
        return new JAXBElement<ExtensionOnlyType>(_WrittenConsent_QNAME, ExtensionOnlyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExtensionOnlyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:SAML:2.0:ac:classes:X509", name = "DeactivationCallCenter")
    public JAXBElement<ExtensionOnlyType> createDeactivationCallCenter(ExtensionOnlyType value) {
        return new JAXBElement<ExtensionOnlyType>(_DeactivationCallCenter_QNAME, ExtensionOnlyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExtensionOnlyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:SAML:2.0:ac:classes:X509", name = "ZeroKnowledge")
    public JAXBElement<ExtensionOnlyType> createZeroKnowledge(ExtensionOnlyType value) {
        return new JAXBElement<ExtensionOnlyType>(_ZeroKnowledge_QNAME, ExtensionOnlyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PrincipalAuthenticationMechanismType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:SAML:2.0:ac:classes:X509", name = "PrincipalAuthenticationMechanism")
    public JAXBElement<PrincipalAuthenticationMechanismType> createPrincipalAuthenticationMechanism(PrincipalAuthenticationMechanismType value) {
        return new JAXBElement<PrincipalAuthenticationMechanismType>(_PrincipalAuthenticationMechanism_QNAME, PrincipalAuthenticationMechanismType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ComplexAuthenticatorType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:SAML:2.0:ac:classes:X509", name = "ComplexAuthenticator")
    public JAXBElement<ComplexAuthenticatorType> createComplexAuthenticator(ComplexAuthenticatorType value) {
        return new JAXBElement<ComplexAuthenticatorType>(_ComplexAuthenticator_QNAME, ComplexAuthenticatorType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExtensionOnlyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:SAML:2.0:ac:classes:X509", name = "ADSL")
    public JAXBElement<ExtensionOnlyType> createADSL(ExtensionOnlyType value) {
        return new JAXBElement<ExtensionOnlyType>(_ADSL_QNAME, ExtensionOnlyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RestrictedPasswordType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:SAML:2.0:ac:classes:X509", name = "RestrictedPassword")
    public JAXBElement<RestrictedPasswordType> createRestrictedPassword(RestrictedPasswordType value) {
        return new JAXBElement<RestrictedPasswordType>(_RestrictedPassword_QNAME, RestrictedPasswordType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SharedSecretChallengeResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:SAML:2.0:ac:classes:X509", name = "SharedSecretChallengeResponse")
    public JAXBElement<SharedSecretChallengeResponseType> createSharedSecretChallengeResponse(SharedSecretChallengeResponseType value) {
        return new JAXBElement<SharedSecretChallengeResponseType>(_SharedSecretChallengeResponse_QNAME, SharedSecretChallengeResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SecretKeyProtectionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:SAML:2.0:ac:classes:X509", name = "SecretKeyProtection")
    public JAXBElement<SecretKeyProtectionType> createSecretKeyProtection(SecretKeyProtectionType value) {
        return new JAXBElement<SecretKeyProtectionType>(_SecretKeyProtection_QNAME, SecretKeyProtectionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PublicKeyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:SAML:2.0:ac:classes:X509", name = "AsymmetricDecryption")
    public JAXBElement<PublicKeyType> createAsymmetricDecryption(PublicKeyType value) {
        return new JAXBElement<PublicKeyType>(_AsymmetricDecryption_QNAME, PublicKeyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PublicKeyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:SAML:2.0:ac:classes:X509", name = "DigSig")
    public JAXBElement<PublicKeyType> createDigSig(PublicKeyType value) {
        return new JAXBElement<PublicKeyType>(_DigSig_QNAME, PublicKeyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LengthType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:SAML:2.0:ac:classes:X509", name = "Length")
    public JAXBElement<LengthType> createLength(LengthType value) {
        return new JAXBElement<LengthType>(_Length_QNAME, LengthType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExtensionOnlyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:SAML:2.0:ac:classes:X509", name = "SubscriberLineNumber")
    public JAXBElement<ExtensionOnlyType> createSubscriberLineNumber(ExtensionOnlyType value) {
        return new JAXBElement<ExtensionOnlyType>(_SubscriberLineNumber_QNAME, ExtensionOnlyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SecurityAuditType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:SAML:2.0:ac:classes:X509", name = "SecurityAudit")
    public JAXBElement<SecurityAuditType> createSecurityAudit(SecurityAuditType value) {
        return new JAXBElement<SecurityAuditType>(_SecurityAudit_QNAME, SecurityAuditType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ActivationLimitDurationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:SAML:2.0:ac:classes:X509", name = "ActivationLimitDuration")
    public JAXBElement<ActivationLimitDurationType> createActivationLimitDuration(ActivationLimitDurationType value) {
        return new JAXBElement<ActivationLimitDurationType>(_ActivationLimitDuration_QNAME, ActivationLimitDurationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link KeySharingType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:SAML:2.0:ac:classes:X509", name = "KeySharing")
    public JAXBElement<KeySharingType> createKeySharing(KeySharingType value) {
        return new JAXBElement<KeySharingType>(_KeySharing_QNAME, KeySharingType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AuthnContextDeclarationBaseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:SAML:2.0:ac:classes:X509", name = "AuthenticationContextDeclaration")
    public JAXBElement<AuthnContextDeclarationBaseType> createAuthenticationContextDeclaration(AuthnContextDeclarationBaseType value) {
        return new JAXBElement<AuthnContextDeclarationBaseType>(_AuthenticationContextDeclaration_QNAME, AuthnContextDeclarationBaseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PublicKeyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:SAML:2.0:ac:classes:X509", name = "AsymmetricKeyAgreement")
    public JAXBElement<PublicKeyType> createAsymmetricKeyAgreement(PublicKeyType value) {
        return new JAXBElement<PublicKeyType>(_AsymmetricKeyAgreement_QNAME, PublicKeyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExtensionOnlyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:SAML:2.0:ac:classes:X509", name = "WTLS")
    public JAXBElement<ExtensionOnlyType> createWTLS(ExtensionOnlyType value) {
        return new JAXBElement<ExtensionOnlyType>(_WTLS_QNAME, ExtensionOnlyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PrivateKeyProtectionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:SAML:2.0:ac:classes:X509", name = "PrivateKeyProtection")
    public JAXBElement<PrivateKeyProtectionType> createPrivateKeyProtection(PrivateKeyProtectionType value) {
        return new JAXBElement<PrivateKeyProtectionType>(_PrivateKeyProtection_QNAME, PrivateKeyProtectionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExtensionOnlyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:SAML:2.0:ac:classes:X509", name = "SharedSecretDynamicPlaintext")
    public JAXBElement<ExtensionOnlyType> createSharedSecretDynamicPlaintext(ExtensionOnlyType value) {
        return new JAXBElement<ExtensionOnlyType>(_SharedSecretDynamicPlaintext_QNAME, ExtensionOnlyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ActivationLimitSessionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:SAML:2.0:ac:classes:X509", name = "ActivationLimitSession")
    public JAXBElement<ActivationLimitSessionType> createActivationLimitSession(ActivationLimitSessionType value) {
        return new JAXBElement<ActivationLimitSessionType>(_ActivationLimitSession_QNAME, ActivationLimitSessionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AuthenticatorTransportProtocolType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:SAML:2.0:ac:classes:X509", name = "AuthenticatorTransportProtocol")
    public JAXBElement<AuthenticatorTransportProtocolType> createAuthenticatorTransportProtocol(AuthenticatorTransportProtocolType value) {
        return new JAXBElement<AuthenticatorTransportProtocolType>(_AuthenticatorTransportProtocol_QNAME, AuthenticatorTransportProtocolType.class, null, value);
    }

}
